# Use Node.js official image
FROM node:18.17.1

# Set working directory
# WORKDIR /app
WORKDIR /usr/src/app

# Copy package.json and install dependencies
# COPY package.json package-lock.json ./
COPY package*.json ./
RUN npm ci --omit=dev
# RUN npm install

# Copy the rest of the app
COPY . .

# Expose port
EXPOSE 80

# Run the app
# CMD ["node", "server.js"]
CMD npm start
